---
title: "Untitled"
output: html_document
date: "2024-02-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#install.packages("DataExplorer")
#install.packages("tidyverse")
#install.packages("palmerpenguins")
```

```{r}
library(palmerpenguins)
library(DataExplorer)
library(tidyverse)
```
```{r}
setwd("/Users/ylawrenc/Desktop")
ptdata<-read.csv(file="pticu.csv", header = T, sep = ",")

ptdata$ethnicity<- as.factor(ptdata$ethnicity)
ptdata$gender<- as.factor(ptdata$gender)
ptdata$icu_admit_source <- as.factor(ptdata$icu_admit_source)
ptdata$icu_stay_type <- as.factor(ptdata$icu_stay_type)
ptdata$icu_type <- as.factor(ptdata$icu_type)
ptdata$apache_3j_bodysystem <- as.factor(ptdata$apache_3j_bodysystem)
ptdata$apache_2_bodysystem <- as.factor(ptdata$apache_2_bodysystem)


```

```{r}
create_report(
  ptdata,
  output_file = "dataexplorer_report.html",
  output_dir = getwd(),
  config = configure_report(),
  report_title = "Data Report"
)
```



```{r}
plot_correlation(
 ptdata,
  type = "all")
```

